# Generated by Django 4.2.4 on 2023-08-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название Книги')),
                ('author', models.CharField(max_length=55, verbose_name='Автор')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('full_description', models.TextField(max_length=255, verbose_name='Полное описание')),
                ('status', models.CharField(choices=[('In_stock', 'В наличие'), ('Out_of_stock', 'Отсутствует'), ('Dev_expected', 'Ожидается поставка')], max_length=16, verbose_name='Cостояние')),
                ('category', models.CharField(choices=[('F', 'Fantasy'), ('D', 'Detective'), ('H', 'Horror'), ('A', 'Adventures'), ('P', 'Poetry'), ('PS', 'Psychology'), ('SL', 'Scientific literature')], max_length=20, verbose_name='Категория')),
                ('date', models.DateField(verbose_name='Дата поставки')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='время модификации')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
